-- INSERT STATEMENTS INTO DESTINATION TABLE
INSERT INTO TEST_SCHEMA.DESTINATION VALUES ('INDIA') 
INSERT INTO TEST_SCHEMA.DESTINATION VALUES ('USA') 
INSERT INTO TEST_SCHEMA.DESTINATION VALUES ('FRANCE') 
INSERT INTO TEST_SCHEMA.DESTINATION VALUES ('LONDON') 
INSERT INTO TEST_SCHEMA.DESTINATION VALUES ('CHINA') 

-- INSERT STATEMENTS INTO TRAVELLER TABLE
INSERT INTO TEST_SCHEMA.TRAVELER VALUES (1, 'John', 'Doe');
INSERT INTO TEST_SCHEMA.TRAVELER VALUES (2, 'Alice', 'Smith');
INSERT INTO TEST_SCHEMA.TRAVELER VALUES (3, 'Bob', 'Johnson');
INSERT INTO TEST_SCHEMA.TRAVELER VALUES (4, 'Emma', 'Williams');
INSERT INTO TEST_SCHEMA.TRAVELER VALUES (5, 'Daniel', 'Brown');
