SELECT * FROM TEST_SCHEMA.TRAVELER;
SELECT * FROM TEST_SCHEMA.DESTINATION;

-- LEFT JOIN THE TWO TABLES TO DISPLAY ALL TRAVELLERS
SELECT *
FROM TEST_SCHEMA.TRAVELER TT
LEFT JOIN TEST_SCHEMA.DESTINATION TD
ON TT.DESTINATION_ID = TD.DESTINATION_ID;